[package]
name = "johansen-null-eigenspectra"
version = "0.1.1"
edition = "2024"

[dependencies]
rand = "0.9.1"
rand_distr = "0.5.1"
nalgebra = "0.33.2"
nalgebra-lapack = { git = "https://github.com/dimforge/nalgebra", package = "nalgebra-lapack", default-features = false }
