# Linux targets: use system-installed LAPACK
[target.x86_64-unknown-linux-gnu]
rustflags = ["-llapack"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-llapack"]

# macOS: use Apple Accelerate framework
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=Accelerate"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=Accelerate"]
